import { H4 } from "../../styles/common/styles";
import {
  Container,
  H2,
  H3,
  Left,
  ListItems,
  Right,
  Text,
  List,
  Strong,
  Button,
} from "../../styles/privacy/Style";

function Privacy() {
  return (
    <>
      <Container>
        <Left>
          <H2>Privacy Policy</H2>
          <Text>Last updated: February 18, 2023</Text>
          <Text>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </Text>
          <Text>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </Text>
          <H2>Interpretation and Definitions</H2>
          <H3>Interpretation</H3>
          <Text>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </Text>
          <H3>Definitions</H3>
          <Text>For the purposes of this Privacy Policy:</Text>
          <List>
            <ListItems>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </ListItems>
            <ListItems>
              Affiliate means an entity that controls, is controlled by or is
              under common control with a party, where "control" means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </ListItems>
            <ListItems>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to CloudSafari Inc., 651 N Broad St,
              Suite 201, Middletown, DE 19709.
            </ListItems>
            <ListItems>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </ListItems>
            <ListItems>Country refers to: Delaware, United States</ListItems>
            <ListItems>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </ListItems>
            <ListItems>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </ListItems>
            <ListItems>Service refers to the Website.</ListItems>
            <ListItems>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </ListItems>
            <ListItems>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </ListItems>

            <ListItems>
              Website refers to CloudSafaris, accessible from
              www.cloudsafaris.com
            </ListItems>
            <ListItems>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </ListItems>
          </List>
          <H2>Collecting and Using Your Personal Data</H2>
          <H3>Types of Data Collected</H3>
          <H4 fontSize="15px" color="black">
            Personal Data
          </H4>
          <text>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </text>
          <ListItems>Email address</ListItems>
          <ListItems>First name and last name</ListItems>
          <ListItems>Phone number</ListItems>
          <ListItems>Usage Data</ListItems>
          <H4 fontSize="15px" color="black">
            Usage Data
          </H4>
          <text>
            Usage Data is collected automatically when using the Service.
          </text>
          <text>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </text>
          <text>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </text>
          <text>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </text>
          <H4 fontSize="15px" color="black">
            Tracking Technologies and Cookies
          </H4>
          <text>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </text>
          <ListItems>
            Cookies or Browser Cookies. A cookie is a small file placed on Your
            Device. You can instruct Your browser to refuse all Cookies or to
            indicate when a Cookie is being sent. However, if You do not accept
            Cookies, You may not be able to use some parts of our Service.
            Unless you have adjusted Your browser setting so that it will refuse
            Cookies, our Service may use Cookies.
          </ListItems>
          <ListItems>
            Web Beacons. Certain sections of our Service and our emails may
            contain small electronic files known as web beacons (also referred
            to as clear gifs, pixel tags, and single-pixel gifs) that permit the
            Company, for example, to count users who have visited those pages or
            opened an email and for other related website statistics (for
            example, recording the popularity of a certain section and verifying
            system and server integrity)
          </ListItems>
          <text>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on Your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close Your
            web browser. You can learn more about cookies on TermsFeed website
            article.
          </text>
          <text>
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </text>
          <ListItems>
            <strong>Necessary / Essential Cookies</strong>
          </ListItems>
          <text>Type: Session Cookies</text>
          <text>Administered by: Us</text>
          <text>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </text>
          <ListItems>
            <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          </ListItems>
          <text>Type: Persistent Cookies</text>
          <text>Administered by: Us</text>
          <text>
            Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website.
          </text>
          <ListItems>
            <strong>Functionality Cookies</strong>
          </ListItems>
          <text>
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy or the Cookies
            section of our Privacy Policy.
          </text>
          <H3>Use of Your Personal Data</H3>
          <text>
            The Company may use Personal Data for the following purposes:
          </text>
          <ListItems>
            To provide and maintain our Service, including to monitor the usage
            of our Service.
          </ListItems>
          <ListItems>
            To manage Your Account: to manage Your registration as a user of the
            Service. The Personal Data You provide can give You access to
            different functionalities of the Service that are available to You
            as a registered user.
          </ListItems>
          <ListItems>
            For the performance of a contract: the development, compliance and
            undertaking of the purchase contract for the products, items or
            services You have purchased or of any other contract with Us through
            the Service.
          </ListItems>
          <ListItems>
            To contact You: To contact You by email, telephone calls, SMS, or
            other equivalent forms of electronic communication, such as a mobile
            application's push notifications regarding updates or informative
            communications related to the functionalities, products or
            contracted services, including the security updates, when necessary
            or reasonable for their implementation.
          </ListItems>
          <ListItems>
            To provide You with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless You have opted not to receive such information.
          </ListItems>
          <ListItems>
            To manage Your requests: To attend and manage Your requests to Us.
          </ListItems>
          <ListItems>
            For business transfers: We may use Your information to evaluate or
            conduct a merger, divestiture, restructuring, reorganization,
            dissolution, or other sale or transfer of some or all of Our assets,
            whether as a going concern or as part of bankruptcy, liquidation, or
            similar proceeding, in which Personal Data held by Us about our
            Service users is among the assets transferred.
          </ListItems>
          <ListItems>
            or other purposes: We may use Your information for other purposes,
            such as data analysis, identifying usage trends, determining the
            effectiveness of our promotional campaigns and to evaluate and
            improve our Service, products, services, marketing and your
            experience.
          </ListItems>
          <text>
            We may share Your personal information in the following situations:
          </text>
          <ListItems>
            With Service Providers: We may share Your personal information with
            Service Providers to monitor and analyze the use of our Service, to
            contact You.
          </ListItems>
          <ListItems>
            For business transfers: We may share or transfer Your personal
            information in connection with, or during negotiations of, any
            merger, sale of Company assets, financing, or acquisition of all or
            a portion of Our business to another company.
          </ListItems>
          <ListItems>
            With Affiliates: We may share Your information with Our affiliates,
            in which case we will require those affiliates to honor this Privacy
            Policy. Affiliates include Our parent company and any other
            subsidiaries, joint venture partners or other companies that We
            control or that are under common control with Us.
          </ListItems>
          <ListItems>
            With business partners: We may share Your information with Our
            business partners to offer You certain products, services or
            promotions
          </ListItems>
          <ListItems>
            With other users: when You share personal information or otherwise
            interact in the public areas with other users, such information may
            be viewed by all users and may be publicly distributed outside.
          </ListItems>
          <ListItems>
            With Your consent: We may disclose Your personal information for any
            other purpose with Your consent.
          </ListItems>
          <H3>Retention of Your Personal Data</H3>
          <text>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </text>
          <text>
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </text>
          <H3>Transfer of Your Personal Data</H3>
          <text>
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </text>
          <text>
            Your consent to this Privacy Policy followed by Your submission of
            such information represents Your agreement to that transfer.
          </text>
          <text>
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of Your data and other personal
            information.
          </text>
          <H3>Delete Your Personal Data</H3>
          <text>
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about You.
          </text>
          <text>
            Our Service may give You the ability to delete certain information
            about You from within the Service.
          </text>
          <text>
            You may update, amend, or delete Your information at any time by
            signing in to Your Account, if you have one, and visiting the
            account settings section that allows you to manage Your personal
            information. You may also contact Us to request access to, correct,
            or delete any personal information that You have provided to Us.
          </text>
          <text>
            Please note, however, that We may need to retain certain information
            when we have a legal obligation or lawful basis to do so.
          </text>
          <H3>Disclosure of Your Personal Data</H3>
          <H4 fontSize="15px" color="black">
            Business Transactions
          </H4>
          <text>
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </text>
          <H4 fontSize="15px" color="black">
            Other legal requirements
          </H4>
          <text>
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to:
          </text>
          <ListItems>Comply with a legal obligation</ListItems>
          <ListItems>
            Protect and defend the rights or property of the Company
          </ListItems>
          <ListItems>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </ListItems>
          <ListItems>
            Protect the personal safety of Users of the Service or the public
          </ListItems>
          <ListItems>Protect against legal liability</ListItems>
          <h3>Security of Your Personal Data</h3>
          <H3>Children's Privacy</H3>
          <H3>Links to Other Websites</H3>
          <H3>Changes to this Privacy Policy</H3>
          <h3>Contact Us</h3>
          <text>
            If you have any questions about this Privacy Policy, You can contact
            us:
          </text>
          <p>
            By email:{" "}
            <a href="mailto:hello@cloudsafaris.com">hello@cloudsafaris.com</a>
          </p>
        </Left>

        <Right>
          <Strong>Still have questions for us?</Strong>
          <Text>Our team has answers and would love to help.</Text>
          <Button>
            Contact Us
            <svg
              aria-hidden="true"
              focusable="false"
              data-prefix="fas"
              data-icon="chevron-right"
              className="svg-inline--fa fa-chevron-right text-sm"
              role="img"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 320 512"
            >
              <path
                fill="currentColor"
                d="M310.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L242.7 256 73.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"
              ></path>
            </svg>
          </Button>
        </Right>
      </Container>
    </>
  );
}

export default Privacy;
